# Copyright (c) Jiaqi Liu
---
name: Site CI/CD

"on":
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  website-ci-cd:
    name: Test & Deploy Website to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
      - name: Bundle up a GitHub Pages deployable
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir .next/server/pages/_next
          mv .next/static/ .next/server/pages/_next/
          cp -r public/images ./.next/server/pages/images
          touch .next/server/pages/.nojekyll
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.next/server/pages
          user_name: QubitPi
          user_email: jack20220723@gmail.com
