# Copyright (c) Jiaqi Liu
---
name: Test

"on":
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-website-build:
    name: Test Website Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
